--- # Bootstrap web servers
- hosts: webservers
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: create index.html
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "Hello World!"
      path: /var/www/html/index.html
  - name: start http web server
    service:
      name: httpd
      state: started
